title: "台灣在地新聞"
description: "讓每個人都能找到想要的資訊，感受友善快樂的傳遞"
baseurl: "/thenewnews"
url: "https://kevin8467.github.io"

lang: zh-TW
timezone: Asia/Taipei

# 文章設定
permalink: /:year/:month/:day/:title/

# 分頁（選填，之後文章多了可以開啟）
# plugins:
#   - jekyll-paginate

# 排除不需要部署的檔案
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
