title: "台灣在地新聞"
description: "讓每個人都能找到想要的資訊，感受友善快樂的傳遞"
baseurl: "/thenewnews"
url: "https://kevin8467.github.io"

lang: zh-TW
timezone: Asia/Taipei

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
